name: Generate Snake Game
on:
  schedule:
    # Executa a ação a cada 12 horas
    - cron: '*/12 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Snake Game from GitHub Contribution Grid
        uses: Platane/snk@v3.2.0
        with:
          # Nome de usuário do GitHub para ler a grade de contribuições (obrigatório)
          github_user_name: intpablo
          # Lista de arquivos a serem gerados
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
